# Backstage override configuration for your cloud deployment

proxy:
  endpoints:
    '/aegis':
      target: 'http://platform-api.aegist.dev:8080'
      changeOrigin: true
      credentials: forward
      secure: false
      allowedHeaders:
        - authorization
        - Authorization
        - x-aegis-user
        - X-Aegis-User
