# Backstage override configuration for your cloud deployment

aegis:
  proxy:
    target: 'https://platform-api.aegist.dev:443'
    changeOrigin: true
    credentials: forward
    allowedHeaders:
      - authorization
      - Authorization
